### ISSUE TITLE
"group ``/df`` does not have a child"

### ISSUE THREAD

**Issue by bmorris3** [timothydmorton/isochrones#101]
Hi @timothydmorton, 

I'm trying to run isochrones from the master branch, and keep running into the following error when I call `mod.fit()`:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pymultinest/run.py", line 212, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/starmodel.py", line 1561, in mnest_loglike
    return self.lnpost(cube)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/starmodel.py", line 509, in lnpost
    return lnpr + self.lnlike(p, **kwargs)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/starmodel.py", line 1499, in lnlike
    i_mags = [self.ic.bc_grid.interp.column_index[b] for b in self.bands]
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/starmodel.py", line 1499, in <listcomp>
    i_mags = [self.ic.bc_grid.interp.column_index[b] for b in self.bands]
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/grid.py", line 135, in interp
    self._interp = DFInterpolator(self.df, filename=filename, is_full=self.is_full)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/grid.py", line 122, in df
    self._df = self.get_df()
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/mist/bc.py", line 41, in get_df
    df = super().get_df(*args, **kwargs)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/isochrones-2.0.1-py3.5.egg/isochrones/bc.py", line 109, in get_df
    df = pd.read_hdf(hdf_filename)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 407, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 782, in select
    return it.get_result()
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 1639, in get_result
    results = self.func(self.start, self.stop, where)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 766, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 3197, in read
    ax = self.read_index("axis{idx}".format(idx=i), start=_start, stop=_stop)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 2765, in read_index
    return self.read_multi_index(key, **kwargs)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 2869, in read_multi_index
    level_codes = self.read_array(label_key, **kwargs)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/pandas/io/pytables.py", line 2731, in read_array
    node = getattr(self.group, key)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/tables/group.py", line 839, in __getattr__
    return self._f_get_child(name)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/tables/group.py", line 711, in _f_get_child
    self._g_check_has_child(childname)
  File "/Users/bmmorris/anaconda/lib/python3.5/site-packages/tables/group.py", line 398, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/df`` does not have a child named ``axis1_label2``
```

Does that look familiar to you? I've tried updating all of the dependencies and continue to hit upon the same error. 

Thanks!

**Comment by bmorris3** [comment]
It looks like deleting my `~/.isochrones` directory did the trick!
