### ISSUE TITLE
nosetest: starmodel.obs is None when running self.emcee_p0()

### ISSUE THREAD

**Issue by mar-ses** [timothydmorton/isochrones#104]
While running the first nosetest I got this error:

-------------------- >> begin captured logging << --------------------
root: WARNING: kwarg RA=299.268036 ignored!
root: ERROR: single starfit calculation failed for /home/sestovic/anaconda3/envs/isochrones/lib/python3.7/site-packages/isochrones/tests/star1.
Traceback (most recent call last):
  File "/home/sestovic/anaconda3/envs/isochrones/lib/python3.7/site-packages/isochrones/starfit.py", line 105, in starfit
    mod.fit(verbose=verbose, overwrite=overwrite, **kwargs)
  File "/home/sestovic/anaconda3/envs/isochrones/lib/python3.7/site-packages/isochrones/starmodel.py", line 642, in fit
    return self.fit_mcmc(**kwargs)
  File "/home/sestovic/anaconda3/envs/isochrones/lib/python3.7/site-packages/isochrones/starmodel.py", line 853, in fit_mcmc
    return self.fit_mcmc_old(**kwargs)
  File "/home/sestovic/anaconda3/envs/isochrones/lib/python3.7/site-packages/isochrones/starmodel.py", line 909, in fit_mcmc_old
    p0 = self.emcee_p0(nwalkers)
  File "/home/sestovic/anaconda3/envs/isochrones/lib/python3.7/site-packages/isochrones/starmodel.py", line 825, in emcee_p0
    for _,n in self.obs.Nstars.items():
AttributeError: 'NoneType' object has no attribute 'Nstars'
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 22 tests in 309.146s

FAILED (errors=1)

Is it possible to use isochrones if we ignore this error, or will it happen every time we try to fit something?

**Comment by mar-ses** [comment]
Ah sorry, it's a copy of this: https://github.com/timothydmorton/isochrones/issues/97
