### ISSUE TITLE
Problem with nosetests isochrones

### ISSUE THREAD

**Issue by kassandra-anderson** [timothydmorton/isochrones#119]
Hello, I am trying to get started with isochrones.  I attempted to run nosetests isochrones and am running into a problem.

I have tried the following:

`conda create -n isochrones numpy numba cython nose pytables pandas flaky pytest`
`conda activate isochrones`
`conda install -c conda-forge multinest pymultinest`
`pip install isochrones`
`nosetests isochrones`

This produces the output below.  Based on the recommendation to some of the other issues raised here, I have also tried specifying `numpy=1.15`, but that creates problems with astropy.

Many thanks!

Output and error:

/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/tests/test_fits.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
....... MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =    5
 dimensionality =    5
 *****************************************************
 ln(ev)=  -2352.1399760148479      +/-  0.56735137479947284     
 Total Likelihood Evaluations:            5
 Sampling finished. Exiting MultiNest
. MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =   20
 dimensionality =    5
 *****************************************************
 ln(ev)=  -41.507141363729289      +/-                       NaN
 Total Likelihood Evaluations:          274
 Sampling finished. Exiting MultiNest
................/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/priors.py:89: RuntimeWarning: divide by zero encountered in true_divide
  sigma = 1.0 / np.sqrt(hn)
../opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/query/catalog.py:60: TableReplaceWarning: converted column 'extKey' from integer to float
  df = self.df.sort_values(by=self._distance_column)
E.......
======================================================================
ERROR: Testing with first entry from Gaia DR1 TGAS table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/tests/test_query.py", line 41, in test_queries
    assert gaia.get_id() == 7632157690368
  File "/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/query/catalog.py", line 73, in get_id
    row = self.closest
  File "/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/query/catalog.py", line 60, in closest
    df = self.df.sort_values(by=self._distance_column)
  File "/opt/anaconda3/envs/isochrones/lib/python3.8/site-packages/isochrones/query/catalog.py", line 55, in df
    raise EmptyQueryError("No good sources found! ({})".format(self.query))
isochrones.query.query.EmptyQueryError: No good sources found! ((45.03433035439128, 0.23539164875137225), pm=(43.75231341609215, -7.641989988351148), epoch=2015.0, radius=5.0 arcsec)

----------------------------------------------------------------------
Ran 34 tests in 121.320s

FAILED (errors=1)

**Comment by timothydmorton** [comment]
I marked this test as skipping with pytest since it is failing, and it hasn't risen to any sort of priority to investigate since the isochrones query functionality is not really central at all.  If you run the tests with `pytest` it should skip it more gracefully.

**Comment by timothydmorton** [comment]
I should probably note in the documentation to run `pytest` rather than `nosetests`; thanks for the heads up!
