### ISSUE TITLE
isochrones: ERROR: single starfit calculation failed  AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found

### ISSUE THREAD

**Issue by JosephKarpinski** [timothydmorton/isochrones#157]
Hi,

Just trying to get this to work.

First test, module flaky was missing.
Installed that and now, things are worse off than before.

/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pandas/core/arraylike.py:358: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'axis1_name[Fe/H]'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
interpolating missing values in evolution tracks (feh=-4.0)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-3.5)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-3.0)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-2.5)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-2.0)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-1.75)': 100%|█| 196/196 [
interpolating missing values in evolution tracks (feh=-1.5)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-1.25)': 100%|█| 196/196 [
interpolating missing values in evolution tracks (feh=-1.0)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-0.75)': 100%|█| 196/196 [
interpolating missing values in evolution tracks (feh=-0.5)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=-0.25)': 100%|█| 196/196 [
interpolating missing values in evolution tracks (feh=0.0)': 100%|█| 196/196 [00
interpolating missing values in evolution tracks (feh=0.25)': 100%|█| 196/196 [0
interpolating missing values in evolution tracks (feh=0.5)': 100%|█| 196/196 [00
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pandas/core/arraylike.py:358: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
Computing dt/deep:   0%|                               | 0/2940 [00:00<?, ?it/s]/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
Computing dt/deep: 100%|████████████████████| 2940/2940 [00:59<00:00, 49.70it/s]
....E/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'axis1_name[Fe/H]'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
building irregular age grid: 100%|██████████| 2940/2940 [00:56<00:00, 52.09it/s]
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
./Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
........./Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/priors.py:89: RuntimeWarning: divide by zero encountered in true_divide
  sigma = 1.0 / np.sqrt(hn)
..F.......
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'flaky')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 7, in <module>
    from flaky import flaky
ModuleNotFoundError: No module named 'flaky'

======================================================================
FAIL: Testing with first entry from Gaia DR1 TGAS table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_query.py", line 38, in test_queries
    assert tm.get_id() == b("03000819+0014074")  # force byte literal b/c that's what gets returned
AssertionError: 
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): vizier.u-strasbg.fr:80
urllib3.connectionpool: DEBUG: http://vizier.u-strasbg.fr:80 "POST /viz-bin/votable HTTP/1.1" 200 3595
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 33 tests in 1320.670s

FAILED (errors=1, failures=1)

pip3 install flaky
Collecting flaky
  Downloading flaky-3.7.0-py2.py3-none-any.whl (22 kB)
Installing collected packages: flaky
Successfully installed flaky-3.7.0

nosetests isochrones
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
.......EE...../Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
./Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
........./Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/priors.py:89: RuntimeWarning: divide by zero encountered in true_divide
  sigma = 1.0 / np.sqrt(hn)
..F.......
======================================================================
ERROR: isochrones.tests.test_fits.test_fitting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 27, in test_fitting
    mod_mist = _check_fitting(StarModel(MIST_Isochrone, **props))
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 74, in _check_fitting
    _fit_mnest(mod)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 80, in _fit_mnest
    mod.fit_multinest(n_live_points=5, max_iter=50, basename=basename, verbose=False)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 797, in fit_multinest
    pymultinest.run(self.mnest_loglike, self.mnest_prior, self.n_params, **mnest_kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pymultinest/run.py", line 277, in run
    lib.run(*args_converted)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found
-------------------- >> begin captured logging << --------------------
isochrones: DEBUG: Building ObservationTree...
isochrones: DEBUG: Adding (3.58, 0.05) @(0.0, 0.0) (-J)
isochrones: DEBUG: Adding (3.22, 0.05) @(0.0, 0.0) (-K)
isochrones: DEBUG: Generating initial p0 for 300 walkers...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: isochrones.tests.test_fits.test_starfit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 46, in test_starfit
    mod.samples
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 1045, in samples
    raise AttributeError("Must run MCMC (or load from file) " + "before accessing samples")
AttributeError: Must run MCMC (or load from file) before accessing samples
-------------------- >> begin captured stdout << ---------------------
Fitting /Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/star1
single starfit...
kwarg RA=299.268036 ignored!
single starfit calculation failed for /Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/star1.
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starfit.py", line 96, in starfit
    mod.fit(verbose=verbose, overwrite=overwrite, **kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 671, in fit
    return self.fit_multinest(**kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 797, in fit_multinest
    pymultinest.run(self.mnest_loglike, self.mnest_prior, self.n_params, **mnest_kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pymultinest/run.py", line 277, in run
    lib.run(*args_converted)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
isochrones: INFO: Testing starfit function with multinest...
isochrones: WARNING: kwarg RA=299.268036 ignored!
isochrones: ERROR: single starfit calculation failed for /Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/star1.
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starfit.py", line 96, in starfit
    mod.fit(verbose=verbose, overwrite=overwrite, **kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 671, in fit
    return self.fit_multinest(**kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 797, in fit_multinest
    pymultinest.run(self.mnest_loglike, self.mnest_prior, self.n_params, **mnest_kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pymultinest/run.py", line 277, in run
    lib.run(*args_converted)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Testing with first entry from Gaia DR1 TGAS table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_query.py", line 38, in test_queries
    assert tm.get_id() == b("03000819+0014074")  # force byte literal b/c that's what gets returned
AssertionError

----------------------------------------------------------------------
Ran 34 tests in 123.157s

FAILED (errors=2, failures=1)

**Comment by JosephKarpinski** [comment]
Still trying to make this work.

Rebooted iMac and ran test again 

nosetests isochrones
/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
.......EE...../Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
./Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
........./Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/priors.py:89: RuntimeWarning: divide by zero encountered in true_divide
  sigma = 1.0 / np.sqrt(hn)
..F.......
======================================================================
ERROR: isochrones.tests.test_fits.test_fitting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 27, in test_fitting
    mod_mist = _check_fitting(StarModel(MIST_Isochrone, **props))
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 74, in _check_fitting
    _fit_mnest(mod)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 80, in _fit_mnest
    mod.fit_multinest(n_live_points=5, max_iter=50, basename=basename, verbose=False)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 797, in fit_multinest
    pymultinest.run(self.mnest_loglike, self.mnest_prior, self.n_params, **mnest_kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pymultinest/run.py", line 277, in run
    lib.run(*args_converted)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found
-------------------- >> begin captured logging << --------------------
isochrones: DEBUG: Building ObservationTree...
isochrones: DEBUG: Adding (3.58, 0.05) @(0.0, 0.0) (-J)
isochrones: DEBUG: Adding (3.22, 0.05) @(0.0, 0.0) (-K)
isochrones: DEBUG: Generating initial p0 for 300 walkers...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: isochrones.tests.test_fits.test_starfit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_fits.py", line 46, in test_starfit
    mod.samples
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 1045, in samples
    raise AttributeError("Must run MCMC (or load from file) " + "before accessing samples")
AttributeError: Must run MCMC (or load from file) before accessing samples
-------------------- >> begin captured stdout << ---------------------
Fitting /Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/star1
single starfit...
kwarg RA=299.268036 ignored!
single starfit calculation failed for /Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/star1.
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starfit.py", line 96, in starfit
    mod.fit(verbose=verbose, overwrite=overwrite, **kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 671, in fit
    return self.fit_multinest(**kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 797, in fit_multinest
    pymultinest.run(self.mnest_loglike, self.mnest_prior, self.n_params, **mnest_kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pymultinest/run.py", line 277, in run
    lib.run(*args_converted)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
isochrones: INFO: Testing starfit function with multinest...
isochrones: WARNING: kwarg RA=299.268036 ignored!
isochrones: ERROR: single starfit calculation failed for /Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/star1.
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starfit.py", line 96, in starfit
    mod.fit(verbose=verbose, overwrite=overwrite, **kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 671, in fit
    return self.fit_multinest(**kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/starmodel.py", line 797, in fit_multinest
    pymultinest.run(self.mnest_loglike, self.mnest_prior, self.n_params, **mnest_kwargs)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/pymultinest/run.py", line 277, in run
    lib.run(*args_converted)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Testing with first entry from Gaia DR1 TGAS table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josephkarpinski/opt/anaconda3/lib/python3.8/site-packages/isochrones/tests/test_query.py", line 38, in test_queries
    assert tm.get_id() == b("03000819+0014074")  # force byte literal b/c that's what gets returned
AssertionError

----------------------------------------------------------------------
Ran 34 tests in 189.402s

FAILED (errors=2, failures=1)
