### ISSUE TITLE
Ran 34 tests and FAILED (failures=1)

### ISSUE THREAD

**Issue by sivdur** [timothydmorton/isochrones#179]
I ran `nosetests isochrones` and had a failure. Also, I got so many deprecation errors. I attached the output (`failures.txt`). And I also attached MultiNest output (`log.txt`).

[failures.txt](https://github.com/timothydmorton/isochrones/files/10098480/failures.txt)
[log.txt](https://github.com/timothydmorton/isochrones/files/10098484/log.txt)

Regards,
Sivan.

**Comment by Astro-Lee** [comment]
I have the same problem.

**Comment by csp421** [comment]
I have the same issue, but mine ran 1 test and failed with one error. I have installed _isochrones_ and have even checked dependencies, all showing that the proper files exist and that each requirement is satisfied. When I run `nosetests isochrones`, I get the following text:

`ERROR: Failure: ModuleNotFoundError (No module named 'isochrones')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 406, in loadTestsFromName
    module = resolve_name(addr.module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'isochrones'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)`

**Comment by csp421** [comment]
Getting the same error. Ran `nosetests isochrones` in the isochrones environment and received 14 failed tests. Showing `33 tests run in 23.592s FAILED (errors=14)`

**Comment by lowestindorm** [comment]
i've the same problem
