### ISSUE TITLE
running nosetests isochrones gives me the following error: ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by kasitennis** [timothydmorton/isochrones#193]
I got the same "ModuleNotFoundError" as below:

$ nosetests isochrones
Traceback (most recent call last):
  File "/Users/sczoo/anaconda2/envs/isochrones/bin/nosetests", line 6, in <module>
    from nose import run_exit
  File "/Users/sczoo/anaconda2/envs/isochrones/lib/python3.12/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/Users/sczoo/anaconda2/envs/isochrones/lib/python3.12/site-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/Users/sczoo/anaconda2/envs/isochrones/lib/python3.12/site-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/Users/sczoo/anaconda2/envs/isochrones/lib/python3.12/site-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
ModuleNotFoundError: No module named 'imp'

**Comment by lowestindorm** [comment]
I‘ve the same problem, do u know how to solve this?

**Comment by timothydmorton** [comment]
FYI I am no longer maintaining this package so can't offer much in the way of direct support.  However, you might try downgrading the version of python (try 3.10 or 3.11) and see if that helps.

**Comment by zqqian** [comment]
I got the same problem in Python 3.12, and I tried to downgrade to Python 3.11. It works.
