### ISSUE TITLE
Test error when multinest is not installed

### ISSUE THREAD

**Issue by migueldvb** [timothydmorton/isochrones#40]
There is an error in test_fits when saving object data to HDF5 if multinest is not available:

```
======================================================================
ERROR: isochrones.tests.test_fits.test_fitting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/miguel/Gaia/isochrones/isochrones/tests/test_fits.py", line 26, in test_fitting
    _check_saving(mod_dar)
  File "/home/miguel/Gaia/isochrones/isochrones/tests/test_fits.py", line 33, in _check_saving
    mod.save_hdf(filename)
  File "/home/miguel/Gaia/isochrones/isochrones/starmodel.py", line 1038, in save_hdf
    attrs._mnest_basename = self._mnest_basename
AttributeError: 'StarModel' object has no attribute '_mnest_basename'
```

**Comment by timothydmorton** [comment]
fixed on current master.  thanks for the help!
