### ISSUE TITLE
Python 3 failure with test_query.py

### ISSUE THREAD

**Issue by migueldvb** [timothydmorton/isochrones#41]
There is a failure when using python 3 caused because astroquer.vizier.Vizier returns bytes instead of strings in some columns and the assertions in `test_query.py` fail.

```
======================================================================
FAIL: Testing with first entry from Gaia DR1 TGAS table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/miguel/Gaia/isochrones/isochrones/tests/test_query.py", line 14, in test_queries
    assert tm.get_id() == '03000819+0014074'
AssertionError: 
-------------------- >> begin captured logging << --------------------
root: WARNING: PyMultiNest not imported.  MultiNest fits will not work.
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): vizier.u-strasbg.fr
requests.packages.urllib3.connectionpool: DEBUG: http://vizier.u-strasbg.fr:80 "POST /viz-bin/votable HTTP/1.1" 200 3558
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.986s

FAILED (failures=1)
```

**Comment by timothydmorton** [comment]
Just getting around to doing some isochrones cleanup, including testing everything with py3.  I just pushed a fix to this onto master.
