### ISSUE TITLE
ValueError when trying to use mod.corner_physical();

### ISSUE THREAD

**Issue by atw5179** [timothydmorton/isochrones#50]
I'm getting this error when trying to use `mod.corner_physical`, my `star.ini` file is set up just like the one in Input[40] of the demo notebook and the `mod.fit()` ran fine.

    WARNING:root:Use Tim's version of corner to plot priors.
    Traceback (most recent call last):
    
    File "<ipython-input-1-bc545b48eeb0>", line 1, in <module>
        runfile('/Users/Austin/star_ini_test.py', wdir='/Users/Austin')
    
    File "/Users/Austin/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
        execfile(filename, namespace)
    
    File "/Users/Austin/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
        exec(compile(f.read(), filename, 'exec'), namespace)
    
    File "/Users/Austin/star_ini_test.py", line 20, in <module>
        mod5.corner_physical();
    
    File "/Users/Austin/anaconda/lib/python3.6/site-packages/isochrones-1.0-py3.6.egg/isochrones/starmodel.py", line 951, in corner_physical
        return self.corner(props, range=rng, **kwargs)
    
    File "/Users/Austin/anaconda/lib/python3.6/site-packages/isochrones-1.0-py3.6.egg/isochrones/starmodel.py", line 927, in corner
        fig = corner.corner(df[params], labels=params, **kwargs)

    File "/Users/Austin/anaconda/lib/python3.6/site-packages/corner-2.0.1-py3.6.egg/corner/corner.py", line 240, in corner
        range=np.sort(range[i]), **hist_kwargs)

    File "/Users/Austin/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py", line 1898, in inner
        return func(ax, *args, **kwargs)

    File "/Users/Austin/anaconda/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6195, in hist
        m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)

    File "/Users/Austin/anaconda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 669, in histogram
    'range parameter must be finite.')

    ValueError: range parameter must be finite.`

This is what my `star.ini` file looks like:

maxAV = 0.217
RA = 283.23581
dec = 41.34304
Teff = 5925, 118
feh = -0.25, 0.15
logg = 4.36, 0.15

[KIC]
g = 12.172, 0
r = 11.749, 0
i = 11.666, 0
z = 11.632, 0

[twomass]
J = 10.797, 0.023
H = 10.516, 0.023
K = 10.424, 0.019

[Lick]
resolution = 0.5
separation_1 = 0.897
PA_1 = 96.871
K_1 = 0.286, 0.1
H_1 = 0.295, 0.1
separatin_2 = 5.765
PA_2 = 174.188
H_2 = 8.058, 0.1
separation_3 = 13.879
PA_3 = 316.172
H_3 = 7.682, 0.1

**Comment by timothydmorton** [comment]
Let me know if you still have this issue with version 1.1, which I've just released.
