### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by ishdutt** [timothydmorton/isochrones#84]
Hi
I am getting this error after running the testing command (`nosetests isochrones`)

```
/home/ishdutt/isochrones/isochrones/starmodel.py:498: RuntimeWarning: divide by zero encountered in log
  lnp += np.log(self.prior('mass', masses[0]))
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =   20
 dimensionality =    5
 *****************************************************
E/home/ishdutt/isochrones/isochrones/mist/grid.py:190: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  skip_blank_lines=True, names=column_names)
/home/ishdutt/isochrones/isochrones/mist/grid.py:195: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = super(MISTModelGrid, self).df_all(phot)
/home/ishdutt/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:2378: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->['[Fe/H]']]

  return pytables.to_hdf(path_or_buf, key, self, **kwargs)
 ln(ev)=  -3191.8158230596973      +/-                       NaN
 Total Likelihood Evaluations:          286
 Sampling finished. Exiting MultiNest
./home/ishdutt/isochrones/isochrones/mist/grid.py:190: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  skip_blank_lines=True, names=column_names)
/home/ishdutt/isochrones/isochrones/mist/grid.py:195: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = super(MISTModelGrid, self).df_all(phot)
/home/ishdutt/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:2378: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->['[Fe/H]']]

======================================================================
ERROR: isochrones.tests.test_fits.test_fitting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishdutt/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ishdutt/isochrones/isochrones/tests/test_fits.py", line 26, in test_fitting
    mod_dar = _check_fitting(StarModel(Dartmouth_Isochrone, **props))
  File "/home/ishdutt/isochrones/isochrones/tests/test_fits.py", line 69, in _check_fitting
    _fit_emcee(mod)
  File "/home/ishdutt/isochrones/isochrones/tests/test_fits.py", line 86, in _fit_emcee
    mod.samples
  File "/home/ishdutt/isochrones/isochrones/starmodel.py", line 934, in samples
    self._make_samples()
  File "/home/ishdutt/isochrones/isochrones/starmodel.py", line 883, in _make_samples
    lnprob = self.sampler.lnprobability[ok, :].ravel()
IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 300
-------------------- >> begin captured logging << --------------------
matplotlib: DEBUG: $HOME=/home/ishdutt
matplotlib: DEBUG: CONFIGDIR=/home/ishdutt/.config/matplotlib
matplotlib: DEBUG: matplotlib data path: /home/ishdutt/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data
matplotlib: DEBUG: loaded rc file /home/ishdutt/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
matplotlib: DEBUG: matplotlib version 3.0.2
matplotlib: DEBUG: interactive is False
matplotlib: DEBUG: platform is linux
matplotlib: DEBUG: loaded modules: ['builtins', 'sys', '_frozen_importlib', '_imp', '_warnings', '_thread', '_weakref', '_frozen_importlib_external', '_io', 'marshal', 'posix', 'zipimport', 'encodings', 'codecs', '_codecs', 'encodings.aliases', 'encodings.utf_8', '_signal', '__main__', 'encodings.latin_1', 'io', 'abc', '_weakrefset', 'site', 'os', 'errno', 'stat', '_stat', 'posixpath', 'genericpath', 'os.path', '_collections_abc', '_sitebuiltins', 'sysconfig', '_sysconfigdata_m_linux_x86_64-linux-gnu', '_bootlocale', '_locale', 'types', 'functools', '_functools', 'collections', 'operator', '_operator', 'keyword', 'heapq', '_heapq', 'itertools', 'reprlib', '_collections', 'weakref', 'collections.abc', 'importlib', 'importlib._bootstrap', 'importlib._bootstrap_external', 'warnings', 'importlib.util', 'importlib.abc', 'importlib.machinery', 'contextlib', 'mpl_toolkits', 'sphinxcontrib', 'encodings.cp437', 're', 'enum', 'sre_compile', '_sre', 'sre_parse', 'sre_constants', 'copyreg', 'pkg_resources', '__future__', 'time', 'zipfile', 'shutil', 'fnmatch', 'zlib', 'bz2', '_compression', 'threading', 'traceback', 'linecache', 'tokenize', 'token', '_bz2', 'lzma', '_lzma', 'pwd', 'grp', 'struct', '_struct', 'binascii', 'pkgutil', 'platform', 'subprocess', 'signal', '_posixsubprocess', 'select', 'selectors', 'math', 'plistlib', 'datetime', '_datetime', 'xml', 'xml.parsers', 'xml.parsers.expat', 'pyexpat.errors', 'pyexpat.model', 'pyexpat', 'xml.parsers.expat.model', 'xml.parsers.expat.errors', 'email', 'email.parser', 'email.feedparser', 'email.errors', 'email._policybase', 'email.header', 'email.quoprimime', 'string', '_string', 'email.base64mime', 'base64', 'email.charset', 'email.encoders', 'quopri', 'email.utils', 'random', 'hashlib', '_hashlib', '_blake2', '_sha3', 'bisect', '_bisect', '_random', 'socket', '_socket', 'urllib', 'urllib.parse', 'email._parseaddr', 'calendar', 'locale', 'tempfile', 'textwrap', 'inspect', 'ast', '_ast', 'dis', 'opcode', '_opcode', 'pkg_resources.extern', 'pkg_resources._vendor', 'pkg_resources.extern.six', 'pkg_resources._vendor.six', 'pkg_resources.extern.six.moves', 'pkg_resources._vendor.six.moves', 'pkg_resources.py31compat', 'pkg_resources.extern.appdirs', 'pkg_resources._vendor.packaging.__about__', 'pkg_resources.extern.packaging', 'pkg_resources.extern.packaging.version', 'pkg_resources.extern.packaging._structures', 'pkg_resources.extern.packaging.specifiers', 'pkg_resources.extern.packaging._compat', 'pkg_resources.extern.packaging.requirements', 'copy', 'pprint', 'pkg_resources.extern.pyparsing', 'pkg_resources.extern.six.moves.urllib', 'pkg_resources.extern.packaging.markers', 'nose', 'nose.core', 'logging', 'atexit', 'unittest', 'unittest.result', 'unittest.util', 'unittest.case', 'difflib', 'unittest.suite', 'unittest.loader', 'unittest.main', 'argparse', 'gettext', 'unittest.runner', 'unittest.signals', 'nose.config', 'optparse', 'configparser', 'nose.util', 'nose.pyversion', 'nose.plugins', 'nose.plugins.base', 'nose.plugins.manager', 'nose.failure', 'pickle', '_compat_pickle', '_pickle', 'nose.plugins.plugintest', 'multiprocessing', 'multiprocessing.context', 'multiprocessing.process', 'multiprocessing.reduction', 'array', '__mp_main__', 'nose.loader', 'nose.case', 'nose.importer', 'imp', 'nose.selector', 'nose.suite', 'nose.proxy', 'nose.result', 'nose.exc', 'nose.plugins.skip', 'nose.plugins.errorclass', 'nose.plugins.deprecated', 'nose.tools', 'nose.tools.nontrivial', 'nose.tools.trivial', 'nose.plugins.builtin', 'nose.plugins.attrib', 'nose.plugins.capture', 'nose.plugins.logcapture', 'nose.plugins.cover', 'nose.plugins.debug', 'pdb', 'cmd', 'bdb', 'code', 'codeop', 'glob', 'nose.plugins.doctests', 'doctest', 'nose.plugins.isolate', 'nose.plugins.failuredetail', 'nose.inspector', 'nose.plugins.prof', 'nose.plugins.testid', 'nose.plugins.multiprocess', 'queue', 'nose.plugins.xunit', 'xml.sax', 'xml.sax.xmlreader', 'xml.sax.handler', 'xml.sax._exceptions', 'xml.sax.saxutils', 'urllib.request', 'http', 'http.client', 'email.message', 'uu', 'email._encoded_words', 'email.iterators', 'ssl', 'ipaddress', '_ssl', 'urllib.error', 'urllib.response', 'nose.plugins.allmodules', 'nose.plugins.collect', 'isochrones', 'isochrones.isochrone', 'isochrones.config', 'pandas', 'numpy', 'numpy._globals', 'numpy.__config__', 'numpy.version', 'numpy._import_tools', 'numpy.add_newdocs', 'numpy.lib', 'numpy.lib.info', 'numpy.lib.type_check', 'numpy.core', 'numpy.core.info', 'numpy.core.multiarray', 'numpy.core.umath', 'numpy.core._internal', 'numpy.compat', 'numpy.compat._inspect', 'numpy.compat.py3k', 'pathlib', 'ntpath', 'ctypes', '_ctypes', 'ctypes._endian', 'numpy.core.numerictypes', 'numbers', 'numpy.core.numeric', 'numpy.core.fromnumeric', 'numpy.core._methods', 'numpy.core.arrayprint', 'numpy.core.defchararray', 'numpy.core.records', 'numpy.core.memmap', 'numpy.core.function_base', 'numpy.core.machar', 'numpy.core.getlimits', 'numpy.core.shape_base', 'numpy.core.einsumfunc', 'numpy.testing', 'numpy.testing._private', 'numpy.testing._private.utils', 'gc', 'numpy.lib.utils', 'numpy.testing._private.decorators', 'numpy.testing._private.nosetester', 'numpy.testing._private.pytesttester', 'numpy.lib.ufunclike', 'numpy.lib.index_tricks', 'numpy.lib.function_base', 'numpy.lib.twodim_base', 'numpy.lib.histograms', 'numpy.matrixlib', 'numpy.matrixlib.defmatrix', 'numpy.linalg', 'numpy.linalg.info', 'numpy.linalg.linalg', 'numpy.linalg.lapack_lite', 'numpy.linalg._umath_linalg', 'numpy.lib.stride_tricks', 'numpy.lib.mixins', 'numpy.lib.nanfunctions', 'numpy.lib.shape_base', 'numpy.lib.scimath', 'numpy.lib.polynomial', 'numpy.lib.arraysetops', 'numpy.lib.npyio', 'numpy.lib.format', 'numpy.lib._datasource', 'numpy.lib._iotools', 'numpy.lib.financial', 'decimal', '_decimal', 'numpy.lib.arrayterator', 'numpy.lib.arraypad', 'numpy.lib._version', 'numpy.core._multiarray_tests', 'numpy._distributor_init', 'numpy._mklinit', 'numpy.fft', 'numpy.fft.info', 'numpy.fft.fftpack', 'numpy.fft.fftpack_lite', 'numpy.fft.helper', 'mkl_fft', 'mkl_fft._pydfti', '_cython_0_29_2', 'cython_runtime', 'mkl_fft._version', 'mkl_fft._numpy_fft', 'numpy.polynomial', 'numpy.polynomial.polynomial', 'numpy.polynomial.polyutils', 'numpy.polynomial._polybase', 'numpy.polynomial.chebyshev', 'numpy.polynomial.legendre', 'numpy.polynomial.hermite', 'numpy.polynomial.hermite_e', 'numpy.polynomial.laguerre', 'numpy.random', 'numpy.random.info', 'numpy.random.mtrand', 'mtrand', 'numpy.ctypeslib', 'numpy.ma', 'numpy.ma.core', 'numpy.ma.extras', 'pytz', 'pytz.exceptions', 'pytz.lazy', 'pytz.tzinfo', 'pytz.tzfile', 'dateutil', 'dateutil._version', 'pandas.compat', 'distutils', 'distutils.version', 'unicodedata', 'pandas.compat.chainmap', 'dateutil.parser', 'dateutil.parser._parser', 'six', 'dateutil.relativedelta', 'dateutil._common', 'dateutil.tz', 'dateutil.tz.tz', 'six.moves', 'dateutil.tz._common', 'dateutil.tz._factories', 'dateutil.parser.isoparser', 'typing', 'typing.io', 'typing.re', 'pandas.compat.numpy', 'pandas._libs', 'pandas._libs.tslibs', 'pandas._libs.tslibs.conversion', 'pandas._libs.tslibs.nattype', 'pandas._libs.tslibs.np_datetime', 'pandas._libs.tslibs.timedeltas', 'pandas._libs.tslibs.offsets', 'pandas._libs.tslibs.ccalendar', 'pandas._libs.tslibs.strptime', 'pandas._libs.tslibs.timezones', 'pandas._libs.tslibs.parsing', 'pandas._libs.tslibs.period', 'pandas._libs.tslibs.frequencies', 'pandas._libs.tslibs.timestamps', 'pandas._libs.tslibs.fields', 'pandas._libs.tslibs.resolution', 'pandas._libs.hashtable', 'pandas._libs.missing', 'pandas._libs.lib', 'fractions', 'pandas._libs.tslib', 'pandas.core', 'pandas.core.config_init', 'pandas.core.config', 'pandas.io', 'pandas.io.formats', 'pandas.io.formats.printing', 'pandas.core.dtypes', 'pandas.core.dtypes.inference', 'pandas.io.formats.console', 'pandas.io.formats.terminal', 'pandas.core.api', 'pandas.core.arrays', 'pandas.core.arrays.array_', 'pandas.core.dtypes.common', 'pandas._libs.algos', 'pandas.core.dtypes.dtypes', 'pandas._libs.interval', 'pandas.core.dtypes.generic', 'pandas.core.dtypes.base', 'pandas.errors', 'pandas.core.arrays.base', 'pandas.compat.numpy.function', 'pandas.util', 'pandas.util._decorators', 'pandas._libs.properties', 'pandas.core.util', 'pandas.core.util.hashing', 'pandas._libs.hashing', 'pandas.core.dtypes.cast', 'pandas.core.dtypes.missing', 'pandas.util._validators', 'pandas.core.ops', 'pandas._libs.ops', 'pandas.core.common', 'pandas.core.missing', 'pandas.core.arrays.categorical', 'pandas.core.accessor', 'pandas.core.algorithms', 'pandas.core.base', 'pandas.core.nanops', 'bottleneck', 'bottleneck.reduce', 'bottleneck.nonreduce', 'bottleneck.nonreduce_axis', 'bottleneck.move', 'bottleneck.slow', 'bottleneck.slow.reduce', 'bottleneck.slow.nonreduce', 'bottleneck.slow.nonreduce_axis', 'bottleneck.slow.move', 'bottleneck.version', 'bottleneck.benchmark', 'bottleneck.benchmark.bench', 'bottleneck.benchmark.autotimeit', 'timeit', 'bottleneck.benchmark.bench_detailed', 'bottleneck.tests', 'bottleneck.tests.util', 'pandas.tseries', 'pandas.tseries.offsets', 'dateutil.easter', 'pandas.core.tools', 'pandas.core.tools.datetimes', 'pandas.core.sorting', 'pandas.core.arrays.datetimes', 'pandas.core.arrays.datetimelike', 'pandas.tseries.frequencies', 'pandas.core.arrays._ranges', 'pandas.core.arrays.interval', 'pandas.util._doctools', 'pandas.core.indexes', 'pandas.core.indexes.base', 'pandas._libs.index', 'pandas._libs.join', 'pandas.core.dtypes.concat', 'pandas.core.indexes.frozen', 'pandas.core.strings', 'pandas.core.arrays.period', 'pandas.core.arrays.timedeltas', 'pandas.core.arrays.integer', 'pandas.core.tools.numeric', 'pandas.core.arrays.sparse', 'pandas._libs.sparse', 'pandas.core.arrays.numpy_', 'pandas.core.groupby', 'pandas.core.groupby.groupby', 'pandas._libs.groupby', 'pandas.core.frame', 'pandas.core.generic', 'json', 'json.decoder', 'json.scanner', '_json', 'json.encoder', 'pandas.core.index', 'pandas.core.indexes.api', 'pandas.core.indexes.category', 'pandas.core.indexes.datetimes', 'pandas.core.indexes.datetimelike', 'pandas.core.tools.timedeltas', 'pandas.core.indexes.numeric', 'pandas.core.indexes.interval', 'pandas.util._exceptions', 'pandas.core.indexes.multi', 'pandas.core.indexes.timedeltas', 'pandas.core.indexes.period', 'pandas.core.indexes.range', 'pandas.core.indexing', 'pandas._libs.indexing', 'pandas.core.internals', 'pandas.core.internals.blocks', 'pandas._libs.internals', 'pandas.core.internals.arrays', 'pandas.core.internals.managers', 'pandas.core.internals.concat', 'pandas.io.formats.format', 'pandas.io.common', 'csv', '_csv', 'mmap', 'pandas.core.internals.construction', 'pandas.core.series', 'pandas.core.indexes.accessors', 'pandas.plotting', 'pandas.plotting._misc', 'pandas.plotting._style', 'pandas.plotting._tools', 'pandas.plotting._core', 'pandas.plotting._compat', 'pandas.plotting._converter', 'matplotlib', 'matplotlib.cbook', 'gzip', 'matplotlib.cbook.deprecation', 'matplotlib.rcsetup', 'matplotlib.fontconfig_pattern', 'pyparsing', 'matplotlib.colors', 'matplotlib._color_data', 'cycler', 'matplotlib._version']
matplotlib: DEBUG: CACHEDIR=/home/ishdutt/.cache/matplotlib
matplotlib.font_manager: DEBUG: Using fontManager instance from /home/ishdutt/.cache/matplotlib/fontlist-v300.json
matplotlib.pyplot: DEBUG: Loaded backend qt5agg version unknown.
matplotlib.pyplot: DEBUG: Loaded backend qt5agg version unknown.
matplotlib.pyplot: DEBUG: Loaded backend Qt5Agg version unknown.
keyring.backend: INFO: Loading KWallet
keyring.backend: INFO: Loading SecretService
keyring.backend: INFO: Loading Windows
keyring.backend: INFO: Loading chainer
keyring.backend: INFO: Loading macOS
asyncio: DEBUG: Using selector: EpollSelector
root: DEBUG: loading B band from UBVRIJHKsKp
root: INFO: Downloading http://stellar.dartmouth.edu/models/isochrones/UBVRIJHKsKp.tgz...
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): stellar.dartmouth.edu:80
urllib3.connectionpool: DEBUG: http://stellar.dartmouth.edu:80 "GET /models/isochrones/UBVRIJHKsKp.tgz HTTP/1.1" 200 46070852
root: INFO: Extracting UBVRIJHKsKp.tgz...
root: INFO: /home/ishdutt/.isochrones/dartmouth/UBVRIJHKsKp.h5 written.
root: DEBUG: loading H band from UBVRIJHKsKp
root: DEBUG: loading J band from UBVRIJHKsKp
root: DEBUG: loading Ks band from UBVRIJHKsKp
root: DEBUG: loading Kp band from UBVRIJHKsKp
root: DEBUG: loading V band from UBVRIJHKsKp
root: DEBUG: loading W1 band from WISE
root: INFO: Downloading http://stellar.dartmouth.edu/models/isochrones/WISE.tgz...
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): stellar.dartmouth.edu:80
urllib3.connectionpool: DEBUG: http://stellar.dartmouth.edu:80 "GET /models/isochrones/WISE.tgz HTTP/1.1" 200 27082742
root: INFO: Extracting WISE.tgz...
root: INFO: /home/ishdutt/.isochrones/dartmouth/WISE.h5 written.
root: DEBUG: loading W2 band from WISE
root: DEBUG: loading W3 band from WISE
root: DEBUG: loading sdss_g band from SDSSugriz
root: INFO: Downloading http://stellar.dartmouth.edu/models/isochrones/SDSSugriz.tgz...
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): stellar.dartmouth.edu:80
urllib3.connectionpool: DEBUG: http://stellar.dartmouth.edu:80 "GET /models/isochrones/SDSSugriz.tgz HTTP/1.1" 200 30263796
root: INFO: Extracting SDSSugriz.tgz...
root: INFO: /home/ishdutt/.isochrones/dartmouth/SDSSugriz.h5 written.
root: DEBUG: loading sdss_i band from SDSSugriz
root: DEBUG: loading sdss_r band from SDSSugriz
root: DEBUG: loading sdss_z band from SDSSugriz
root: INFO: Downloading files for dartmouth model grid: ('dartmouth.tri',)...
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): zenodo.org:443
urllib3.connectionpool: DEBUG: https://zenodo.org:443 "GET /record/1002927/files/dartmouth.tri HTTP/1.1" 200 179548599
root: DEBUG: /home/ishdutt/.isochrones/dartmouth.tri verified.
root: DEBUG: /home/ishdutt/.isochrones/dartmouth.tri verified.
root: DEBUG: loading B band from UBVRIJHKsKp
root: DEBUG: loading H band from UBVRIJHKsKp
root: DEBUG: loading J band from UBVRIJHKsKp
root: DEBUG: loading Ks band from UBVRIJHKsKp
root: DEBUG: loading Kp band from UBVRIJHKsKp
root: DEBUG: loading V band from UBVRIJHKsKp
root: DEBUG: loading W1 band from WISE
root: DEBUG: loading W2 band from WISE
root: DEBUG: loading W3 band from WISE
root: DEBUG: loading sdss_g band from SDSSugriz
root: DEBUG: loading sdss_i band from SDSSugriz
root: DEBUG: loading sdss_r band from SDSSugriz
root: DEBUG: loading sdss_z band from SDSSugriz
root: DEBUG: Building ObservationTree...
root: DEBUG: loading B band from UBVRIJHKsKp
root: DEBUG: loading H band from UBVRIJHKsKp
root: DEBUG: loading J band from UBVRIJHKsKp
root: DEBUG: loading Ks band from UBVRIJHKsKp
root: DEBUG: loading Kp band from UBVRIJHKsKp
root: DEBUG: loading V band from UBVRIJHKsKp
root: DEBUG: loading W1 band from WISE
root: DEBUG: loading W2 band from WISE
root: DEBUG: loading W3 band from WISE
root: DEBUG: loading sdss_g band from SDSSugriz
root: DEBUG: loading sdss_i band from SDSSugriz
root: DEBUG: loading sdss_r band from SDSSugriz
root: DEBUG: loading sdss_z band from SDSSugriz
root: DEBUG: Adding (5.7, 0.05) @(0.0, 0.0) (-B)
root: DEBUG: Adding (5.0, 0.05) @(0.0, 0.0) (-V)
root: DEBUG: loading B band from UBVRIJHKsKp
root: DEBUG: loading H band from UBVRIJHKsKp
root: DEBUG: loading J band from UBVRIJHKsKp
root: DEBUG: loading Ks band from UBVRIJHKsKp
root: DEBUG: loading Kp band from UBVRIJHKsKp
root: DEBUG: loading V band from UBVRIJHKsKp
root: DEBUG: loading W1 band from WISE
root: DEBUG: loading W2 band from WISE
root: DEBUG: loading W3 band from WISE
root: DEBUG: loading sdss_g band from SDSSugriz
root: DEBUG: loading sdss_i band from SDSSugriz
root: DEBUG: loading sdss_r band from SDSSugriz
root: DEBUG: loading sdss_z band from SDSSugriz
root: DEBUG: lnp=-inf for mass=0.07364209616255452 (system 0)
root: DEBUG: lnp=-inf for mass=0.09472299751571511 (system 0)
root: DEBUG: lnp=-inf for mass=0.08279029013666821 (system 0)
root: DEBUG: lnp=-inf for mass=0.08572067907687628 (system 0)
root: DEBUG: lnp=-inf for mass=0.022287825231807973 (system 0)
root: DEBUG: lnp=-inf for mass=0.04107363248729817 (system 0)
root: DEBUG: lnp=-inf for mass=-0.17520661852071062 (system 0)
root: DEBUG: lnp=-inf for mass=-0.06686122142821965 (system 0)
root: DEBUG: lnp=-inf for mass=0.06762872088135957 (system 0)
root: DEBUG: lnp=-inf for mass=0.0756183813871209 (system 0)
root: DEBUG: lnp=-inf for mass=0.08166142590099269 (system 0)
root: DEBUG: lnp=-inf for mass=0.06708507827152216 (system 0)
root: DEBUG: lnp=-inf for mass=0.04126274714040887 (system 0)
root: DEBUG: lnp=-inf for mass=0.01264045125143698 (system 0)
root: DEBUG: lnp=-inf for mass=0.05561829329054169 (system 0)
root: DEBUG: lnp=-inf for mass=0.0793478465050116 (system 0)
root: DEBUG: lnp=-inf for mass=0.07881308263041398 (system 0)
root: DEBUG: lnp=-inf for mass=-0.06191983941165646 (system 0)
root: DEBUG: lnp=-inf for mass=-0.35289160665426134 (system 0)
root: DEBUG: lnp=-inf for mass=0.08743250603243423 (system 0)
root: DEBUG: lnp=-inf for mass=0.07410523621355075 (system 0)


--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 15 tests in 1736.291s

FAILED (errors=1)

```
I have tried reinstalling the package several times but still the same error persist.Due to this error (I'm not sure though) some of the commands in starmodel object from the demo.ipynb notebook is not running 
 `mod = StarModel(mist, Teff=(5700,100), logg=(4.5,0.1), feh=(0.0,0.1))
mod.fit(basename='spec_demo')`

**Comment by timothydmorton** [comment]
Sorry for the troubles you've been having; hang tight for an imminent v2.0 release and then try again!

**Comment by timothydmorton** [comment]
I'm assuming this is OK now; feel free to re-open if not.
